"""add manufacturing_date to ingredient_lots

Revision ID: 930fae821004
Revises: c9e4b90a1ac1
Create Date: 2026-07-24 00:16:13.997382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '930fae821004'
down_revision: Union[str, None] = 'c9e4b90a1ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_lots', sa.Column('manufacturing_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_lots', 'manufacturing_date')
    # ### end Alembic commands ###
