"""tenant status, rbac roles, soft delete, audit log

Revision ID: dcd771f1e2a1
Revises: 930fae821004
Create Date: 2026-08-05 23:03:14.839398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd771f1e2a1'
down_revision: Union[str, None] = '930fae821004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Cria os tipos ENUM explicitamente — op.add_column/alter_column NÃO
    # criam o tipo sozinhos no PostgreSQL (ajuste manual sobre o autogenerate)
    sa.Enum('active', 'past_due', 'blocked', name='tenant_status').create(op.get_bind())
    sa.Enum('super_admin', 'tenant_admin', 'tenant_user', name='user_role').create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_name', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.add_column('ingredient_lots', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingredient_lots', sa.Column('deletion_reason', sa.Text(), nullable=True))
    op.add_column('ingredient_lots', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_ingredient_lots_deleted_by_id_users'), 'ingredient_lots', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('ingredients', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingredients', sa.Column('deletion_reason', sa.Text(), nullable=True))
    op.add_column('ingredients', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_ingredients_deleted_by_id_users'), 'ingredients', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('deletion_reason', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('deleted_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_products_deleted_by_id_users'), 'products', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('tenants', sa.Column('status', sa.Enum('active', 'past_due', 'blocked', name='tenant_status'), server_default='active', nullable=False))
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # Converte valores antigos (ex: 'admin') antes de trocar o tipo da coluna
    op.execute(
        "UPDATE users SET role = 'tenant_admin' "
        "WHERE role NOT IN ('super_admin', 'tenant_admin', 'tenant_user')"
    )
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('super_admin', 'tenant_admin', 'tenant_user', name='user_role'),
               existing_nullable=False,
               server_default='tenant_user',
               postgresql_using='role::user_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'tenant_admin', 'tenant_user', name='user_role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               server_default=None,
               postgresql_using='role::text')
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tenants', 'status')
    op.drop_constraint(op.f('fk_products_deleted_by_id_users'), 'products', type_='foreignkey')
    op.drop_column('products', 'deleted_by_id')
    op.drop_column('products', 'deletion_reason')
    op.drop_column('products', 'deleted_at')
    op.drop_constraint(op.f('fk_ingredients_deleted_by_id_users'), 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'deleted_by_id')
    op.drop_column('ingredients', 'deletion_reason')
    op.drop_column('ingredients', 'deleted_at')
    op.drop_constraint(op.f('fk_ingredient_lots_deleted_by_id_users'), 'ingredient_lots', type_='foreignkey')
    op.drop_column('ingredient_lots', 'deleted_by_id')
    op.drop_column('ingredient_lots', 'deletion_reason')
    op.drop_column('ingredient_lots', 'deleted_at')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

    # Remove os tipos ENUM criados no upgrade
    sa.Enum(name='user_role').drop(op.get_bind())
    sa.Enum(name='tenant_status').drop(op.get_bind())
